version: "3.6"

services:

  mariadb:
    image: mariadb:10.4
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
    - ./databases/mariadb:/var/lib/mysql

  php:
    build:
      context: DevBox.DockerFile
    ports:
      - 80:80
   link:
      - mariadb
