version: "3.6"

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      MARIADB_DATABASE: testdb
      MARIADB_USER: test_user
      MARIADB_PASSWORD: test_pass

  php-apache:
    image: php:8.0-apache
    ports:
      - 81:81
