version: "3"

services:

  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
        dockerfile: DevBox.DockerFile
      depends_on:
        - db
      ports:
        - 8000:80

  mysql:
    container_name: mysql
    build:
      context: ./
        dockerfile: MySQLDev.DockerFile
       ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
       - ./databases/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
     ports:
       - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: test_user
      PMA_PASSWORD: test_pass

