version: "3.6"

services:

  db:
    image: mariadb
    ports:
      - 3808:3808
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      MARIADB_DATABASE: testdb
      MARIADB_USER: test_user
      MARIADB_PASSWORD: test_pass
    volumes:
        - db:/var/lib/mysql

  php-apache:
    build:
      context: php
    ports:
      - 81:81
    links:
      - 'db'

  

volumes:
   db:
